[package]
name = "rb_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
clap = { version = "4.5.0", features = ["derive"] }
rayon = "1.5.1"
uint = "0.9.5"